### PR TITLE
Update tFPDF version

### LINKED ISSUE #117: Update tFPDF
We are on version 1.24. The new version seems to be here:

https://github.com/DocnetUK/tfpdf

Latest is 2.0.6.

### PR DESCRIPTION
**Pull request by alexsanford**
Fixes #117 

This PR updates the version of the [tFPDF library](https://github.com/DocnetUK/tfpdf) from 1.24 to. 2.1.0 (the latest version).

Unfortunately, we have two methods in Sensei Certificates that use the tFPDF library with very similar code. Ideally, the common functionality should be extracted, but maybe in a different PR.

However, I did extract some functionality that was changed in the new version, to prevent further code duplication.

The meaningful changes are in `classes/*`. All of the changes in `lib/*` are from upgrading the tFPDF code.

## Concerns

The biggest concern is that the new version of tFPDF does not support PHP 5.3 or lower. If we want to maintain support in this extension for earlier versions of PHP, we may have to consider modifying the library to address the compatibility issues.

Also, Sensei Certificates appears to have had the ability to save a PDF to a file. When I tried to test this, it threw a Fatal and didn't work:

```
PHP Fatal error:  Uncaught Error: Call to undefined method WooThemes_Sensei_PDF_Certificate::get_certificate_template_path() in /var/www/html/wp-content/plugins/sensei-certificates/classes/class-woothemes-sensei-pdf-certificate.php:149
```

I removed this functionality, because we are not using it in our own extension, and it seems that no one else is using it because it is broken. That said, I wonder if we should be more cautious about removing it?

(Also note the `$path` parameter that I've left in the `generate_pdf` functions for potential backward compatibility.)

## Testing

- Create a certificate template and add it to a course.

- When viewing the template in wp-admin, click on the Preview button. You should see the PDF preview for the certificate template.

- Complete the course.

- View the certificates in wp-admin. You should see the certificate that you earned.

- Click on View Certificate. You should see the PDF of the certificate.

### CODE REVIEW

**Comment by alexsanford** [comment]
> I was weary of doing that too, because of that PHP version requirement. 

Yeah, agreed. We could choose, however, not to support older PHP versions for this extension. It's a discussion we've had a few times (in the context of Sensei as a whole), and I don't know that we've come up with a definitive answer.

Based on usage data though, we only have a couple Sensei users sending usage data from PHP 5.3, and none from 5.2. Since usage data is opt-in, we can't be sure how many users there are on these versions, but it seems like the number is probably quite low.

@jom do you want to weigh in on this?

**Comment by alexsanford** [comment]
After some discussion with @jom I'm closing this PR and setting the priority of #117 to Low.

The main problem brought up in #117 (deprecated constructors) has been fixed as per https://github.com/woocommerce/sensei-certificates/issues/117#issuecomment-296596670. It appears that the new issue (see https://github.com/woocommerce/sensei-certificates/issues/117#issuecomment-376896458) is not actually related to this PDF lib version.

Since we don't have any immediate need to upgrade this in order to fix a problem, given that it would break backwards compatibility with PHP 5.2 and 5.3 (both of which are supported by Sensei core), it doesn't make sense to move forward with this PR.

**Comment by jom** [comment]
Now that we're PHP 5.6+, I'm reopening this PR.

**Comment by jom** [comment]
@alexsanford I've updated this with:
- Slightly newer version fo tfpdf.
- Modifications for VIP (seem easier now that we don't allow saving the file in filesystem).
- Updated font we use for MB strings, which seems to fix #169

**Review by yscik — APPROVED** [review]

**Comment by donnapep** [comment]
Houston, I think we have a problem. I'm getting a critical error when viewing a certificate or certificate template:

```
PHP Fatal error:  require_once(): Failed opening required '/Users/donnapep/Local Sites/sensei/app/public/wp-content/plugins/sensei-certificates/classes/../lib/tfpdf/src/tFPDF/PDF.php' (include_path='.:/usr/share/php:/www/wp-content/pear') in /Users/donnapep/Local Sites/sensei/app/public/wp-content/plugins/sensei-certificates/classes/class-woothemes-sensei-certificates-tfpdf.php on line 22
```

**Comment by jom** [comment]
@donnapep Are you using the built version or directly from GitHub? This was an old PR so we'll need to update the built files in `composer.json`. I'm not able to reproduce from GitHub `master`, though.

**Comment by donnapep** [comment]
Yup, just updated my previous comment. Only the built version is doing this.

**Comment by jom** [comment]
PR to fix this https://github.com/woocommerce/sensei-certificates/pull/256

**Pull request merged**
