### PR TITLE
Certificate data field enhancements

### PR DESCRIPTION
**Pull request by misenhower**
This is related to issue #93.

These changes add the following two filters:
- `sensei_certificate_data_fields` - This filter allows other plugins to add (or remove) data fields that appear in the Certificate Template editor.
- `sensei_certificate_data_field_value` - This filter is applied to the content of each of the data fields before they are written to the PDF. It provides the following five arguments:
  - `$field_value` - The field content (which will be written to the PDF).
  - `$field_key` - The name of the field the content is being written for. (This could be used to, for example, hide specific data fields under certain conditions.)
  - `$is_preview` - Boolean, true indicates that the certificate being generated is a template preview. When generating a template preview, `$student` and `$course` will be null.
  - `$student` - a WP_User object, the student the certificate is being generated for.
  - `$course` - a WP_Post object, the course the certificate is being generated for.

As an example, a third-party plugin could add a new field as follows:

``` php
add_filter('sensei_certificate_data_fields', 'my_sensei_certificate_data_fields');

function my_sensei_certificate_data_fields($data_fields)
{
    $data_fields['credit_hours'] = array(
        'type' => 'text',
        'position_label' => 'Credit Hours Position',
        'position_description' => 'Optional position of the Credit Hours text',
        'text_label' => 'Credit Hours Text',
        'text_description' => 'Text to display in the Credit Hours area.',
        'text_placeholder' => 'Credit Hours: {{credit_hours}}',
    );

    return $data_fields;
}
```

The `{{credit_hours}}` template tag in this example could be enabled as follows:

``` php
add_filter('sensei_certificate_data_field_value', 'my_sensei_certificate_data_field_value', 10, 5);

function my_sensei_certificate_data_field_value($field_value, $field_key, $is_preview, $student, $course)
{
    if ($is_preview)
    {
        // Just use a sample value of 3
        $credit_hours = '3';
    }
    else
    {
        // Get our custom meta value
        $credit_hours = get_post_meta($course->ID, '_credit_hours', true);
    }

    // If this is the "credit_hours" data field, return an empty string if credit hours weren't specified for this course.
    // This prevents the "Credit Hours:" text from appearing when we don't know how many credit hours the course has.
    if (!$credit_hours && $field_key == 'credit_hours')
        return '';

    return str_replace('{{credit_hours}}', $credit_hours, $field_value);
}
```

### CODE REVIEW

**Comment by PDowney** [comment]
This is such an important feature that is shockingly missing. I'm currently using the certificates on a education site that issues CE credits to licensed professionals, but the certificates require their license number to the printer on the certificate in addition to their name.

The fact that we cannot easily add other user entered fields is crazy.

**Comment by AaronSoap** [comment]
Hey,

I am working on a site at the moment that needs the students name to be generated at the time the certificate is made and not change when the users changes their name in the admin.

This would help so much with that. As above said, its a bit mad that this wasn't already a thing.

Just a small addition, would it be possible to send along the certificate id as well? My thoughts are i'm going to store the name of the student as meta on the certificate at the time of generation. (if student name meta doesnt already exist.)

+1

**Comment by PDowney** [comment]
I wouldn’t hold my breath. They seem to have abandoned this extension along with most of Sensei.

 I too noticed that students can retroactively change the name printed on the certificate, I’m sure the sensei team noticed this as well but it’s a bit trickier to fix than they wanted to dedicate time to.  There's so many improvements that need to be made to this specific extension, and honestly I'm shocked that it hasn't been merged with Sensei as a whole because of how important certificates are to the overall LMS.

**Comment by jairsnow** [comment]
Hey, i've tested this commit and seems good, there only 2 minor error eith a couple of variables that are not instantiated.
I see that are no improvement about the enhancements since 2016. I will post soon a new commit that follow this line with the minor fix.

**Comment by misenhower** [comment]
Hey thanks, I will check that out when I have a moment. I could probably add those changes in as part of this pull request.

As this pull request approaches two years of age, I'm not sure if it will ever be merged 😄  I have, however, been able to make a mostly-functional version of these changes that works as a separate, standalone plugin. If anyone is interested in that, please feel free to contact me at matt@isenhower.com for a quote.

Also, when building customizations for clients I've found it was useful to have a couple more variables passed to the `sensei_certificate_data_field_value` filter (including the original field definition and the configured parameters for that field). I will add those variables to the filter and update this PR with those changes when I get a chance.

**Comment by m1r0** [comment]
Hey, @misenhower. 👋 

We are planning to give more love to Sensei and I think you've done a ✨ great job ✨ with this feature! So, thank you! 🙏

I would like to help and push it forward.

If you don't have the time, I can assist by rebasing the branch, nailing down any bugs that may come up, and doing some refactoring where needed.

Let me know if you still want to continue working on this or if you are ok with me joining the fun (you may need to give me write permission to your fork or I can make a new branch if that's ok).

**Comment by m1r0** [comment]
@misenhower We will continue the work on this in #292. Feel free to follow up there. :beers:

**Pull request closed without merging**
